import { internalAction } from "./_generated/server";
import { v } from "convex/values";
import { getMessage, createReplyDraft } from "./graphClient";
import { classifyEmail } from "./outlookRules";
import { internal } from "./_generated/api";

/**
 * Internal action that:
 * - Fetches a message from Outlook via Microsoft Graph
 * - Classifies it using keyword rules
 * - Persists the classification in Convex
 * - (Placeholder) Generates an AI draft reply and creates a reply draft in Outlook
 *
 * This will be invoked from the webhook processing pipeline once wired up.
 */
export const processNewOutlookMessage = internalAction({
  args: {
    userId: v.id("users"),
    mailbox: v.string(),
    messageId: v.string(),
  },
  handler: async (ctx, args) => {
    // Fetch full message details
    const message = await getMessage(args.mailbox, args.messageId);

    const subject: string | undefined = message.subject ?? undefined;
    const bodyPreview: string | undefined = message.bodyPreview ?? undefined;
    const fromAddress: string | undefined = message.from?.emailAddress?.address;
    const receivedAt: number = message.receivedDateTime
      ? Date.parse(message.receivedDateTime)
      : Date.now();

    const classification = classifyEmail(subject, bodyPreview);

    await ctx.runMutation(internal.outlookRules.saveClassifiedEmail, {
      userId: args.userId,
      messageId: args.messageId,
      mailbox: args.mailbox,
      subject,
      from: fromAddress,
      receivedAt,
      importance: classification.importance,
      tags: classification.tags,
      folder: classification.suggestedFolder,
      status: "classified",
    });

    // Placeholder AI draft generation: in a later step, call your LLM here.
    // For now, just create a minimal reply draft that the user can see in Outlook.
    const draftBody =
      `<p>Hi,</p>` +
      `<p>This is a placeholder draft reply generated by Pretium Process. ` +
      `Please review and customize before sending.</p>` +
      `<p>Original subject: ${subject ?? "(no subject)"}.</p>`;

    await createReplyDraft(args.mailbox, args.messageId, draftBody);

    // Optionally we could update status to "responded" once a proper AI integration is in place.
  },
});

